openapi: 3.0.0
info:
  title: Account API
  version: 1.0.0
  description: API para la gestión de cuentas bancarias.
servers:
  - url: http://localhost:8081
    description: Development server

paths:
  /accounts:
    get:
      summary: Obtiene todas las cuentas
      tags:
        - Accounts
      operationId: getAllAccounts
      responses:
        '200':
          description: Lista de cuentas obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Crea una nueva cuenta
      tags:
        - Accounts
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
      responses:
        '201':
          description: Cuenta creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /accounts/account-number/{accountNumber}:
    get:
      summary: Obtiene una cuenta por su número de cuenta
      tags:
        - Accounts
      operationId: getAccountByAccountNumber
      parameters:
        - in: path
          name: accountNumber
          schema:
            type: string
          required: true
          description: Número de cuenta
      responses:
        '200':
          description: Cuenta obtenida exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '404':
          description: Cuenta no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Elimina una cuenta por su número de cuenta
      tags:
        - Accounts
      operationId: deleteAccountByAccountNumber
      parameters:
        - in: path
          name: accountNumber
          schema:
            type: string
          required: true
          description: Número de cuenta
      responses:
        '204':
          description: Cuenta eliminada exitosamente (No Content)
        '404':
          description: Cuenta no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Actualiza una cuenta existente.
      tags:
        - Accounts
      operationId: updateAccountByAccountNumber
      parameters:
        - in: path
          name: accountNumber
          schema:
            type: string
          required: true
          description: Número de cuenta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
      responses:
        '200':
          description: Cuenta actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Cuenta no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


  /accounts/account-number/{accountNumber}/balance:
    get:
      summary: Obtiene el saldo disponible de una cuenta por su número de cuenta
      tags:
        - Accounts
      operationId: getBalanceByAccountNumber
      parameters:
        - in: path
          name: accountNumber
          schema:
            type: string
          required: true
          description: Número de cuenta
      responses:
        '200':
          description: Cuenta obtenida exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '404':
          description: Cuenta no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /accounts/account-number/{accountNumber}/balance/increase:
    patch:
      summary: Incrementa el saldo disponible de una cuenta por su número de cuenta
      tags:
        - Accounts
      operationId: increaseBalanceByAccountNumber
      parameters:
        - in: path
          name: accountNumber
          schema:
            type: string
          required: true
          description: Número de cuenta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BalanceUpdateRequest'
      responses:
        '200':
          description: Saldo de la cuenta actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '400':
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Cuenta no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /accounts/account-number/{accountNumber}/balance/reduction:
    patch:
      summary: Reduce el saldo disponible de una cuenta por su número de cuenta
      tags:
        - Accounts
      operationId: reduceBalanceByAccountNumber
      parameters:
        - in: path
          name: accountNumber
          schema:
            type: string
          required: true
          description: Número de cuenta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BalanceUpdateRequest'
      responses:
        '200':
          description: Saldo de la cuenta actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '400':
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Cuenta no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /accounts/account-number/{accountNumber}/deposit:
    post:
      summary: Deposita dinero en una cuenta por su número de cuenta
      tags:
        - Accounts
      operationId: depositByAccountNumber
      parameters:
        - in: path
          name: accountNumber
          schema:
            type: string
          required: true
          description: Número de cuenta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositRequest'
      responses:
        '200':
          description: Depósito realizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Cuenta no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /accounts/account-number/{accountNumber}/withdrawal:
    post:
      summary: Retira dinero de una cuenta por su número de cuenta
      tags:
        - Accounts
      operationId: withdrawByAccountNumber
      parameters:
        - in: path
          name: accountNumber
          schema:
            type: string
          required: true
          description: Número de cuenta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawalRequest'
      responses:
        '200':
          description: Retiro realizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Solicitud inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Cuenta no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /accounts/account-number/{accountNumber}/transactions:
    get:
      summary: Obtiene las transacciones de una cuenta por su número de cuenta
      tags:
        - Accounts
      operationId: getTransactionsByAccountNumber
      parameters:
        - in: path
          name: accountNumber
          schema:
            type: string
          required: true
          description: Número de cuenta
      responses:
        '200':
          description: Lista de transacciones obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionResponse'
        '404':
          description: Cuenta no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    AccountRequest:
      type: object
      required:
        - accountType
        - currencyType
        - balance
        - status
        - customerDni
      properties:
        accountType:
          type: string
          enum: [SAVINGS, CHECKING, FIXED_TERM]
          description: Tipo de cuenta
        currencyType:
          type: string
          enum: [PEN, USD]
          description: Tipo de moneda
        balance:
          type: number
          format: decimal
          description: Saldo de la cuenta
        status:
          type: string
          enum: [ACTIVE, CLOSED, BLOCKED]
          description: Estado de la cuenta
        customerDni:
          type: string
          description: DNI del cliente
        movementsThisMonth:
          type: integer
          description: Movimientos del mes
        maxMovementsFeeFreeThisMonth:
          type: integer
          description: Máximo de movimientos libres de comisión del mes
        isCommissionFeeActive:
          type: boolean
          description: Consultar si la comisión por movimiento está activa
        movementCommissionFee:
          type: number
          format: decimal
          description: Comisión por movimiento

        #Savings account fields
        monthlyMovementsLimit:
          type: integer
          description: Límite de movimientos mensuales (Solo para cuentas de ahorro)

        #CheckingAccount fields
        maintenanceFee:
          type: number
          format: decimal
          description: Comisión de mantenimiento (Solo para cuentas corrientes)
        holders:
          type: array
          items:
            type: string
          description: Lista de titulares (Solo para cuentas corrientes)
        authorizedSigners:
          type: array
          items:
            type: string
          description: Lista de firmantes autorizados (Solo para cuentas corrientes)

        #FixedTerm fields
        allowedWithdrawal:
          type: string
          format: date
          description: Fecha permitida de retiro (Solo para cuentas a plazo fijo)

    # Requests para depositar y retirar
    DepositRequest:
      type: object
      required:
        - currencyType
        - amount
      properties:
        currencyType:
          type: string
          enum: [PEN, USD]
          description: Tipo de moneda.
        amount:
          type: number
          format: decimal
          description: Monto a depositar.

    WithdrawalRequest:
      type: object
      required:
        - currencyType
        - amount
      properties:
        currencyType:
          type: string
          enum: [PEN, USD]
          description: Tipo de moneda.
        amount:
          type: number
          format: decimal
          description: Monto a retirar.

    BalanceUpdateRequest:
      type: object
      required:
        - balance
      properties:
        balance:
          type: number
          format: decimal
          description: Nuevo saldo de la cuenta

    # Responses
    AccountResponse:
      type: object
      properties:
        id:
          type: string
          description: ID de la cuenta
        accountNumber:
          type: string
          description: Número de cuenta
        accountType:
          type: string
          enum: [SAVINGS, CHECKING, FIXED_TERM]
          description: Tipo de cuenta
        currencyType:
          type: string
          enum: [PEN, USD]
          description: Tipo de moneda
        balance:
          type: number
          format: decimal
          description: Saldo de la cuenta
        status:
          type: string
          enum: [ACTIVE, CLOSED, BLOCKED]
          description: Estado de la cuenta
        createdAt:
          type: string
          format: date-time
          description: Fecha de creación de la cuenta
        customerDni:
          type: string
          description: DNI del cliente
        movementsThisMonth:
          type: integer
          description: Movimientos del mes
        maxMovementsFeeFreeThisMonth:
          type: integer
          description: Máximo de movimientos libres de comisión del mes
        isCommissionFeeActive:
          type: boolean
          description: Consultar si la comisión por movimiento está activa
        movementCommissionFee:
          type: number
          format: decimal
          description: Comisión por movimiento

        #Savings account fields
        monthlyMovementsLimit:
          type: integer
          description: Límite de movimientos mensuales (Solo para cuentas de ahorro)

        #CheckingAccount fields
        maintenanceFee:
          type: number
          format: decimal
          description: Comisión de mantenimiento (Solo para cuentas corrientes)
        holders:
          type: array
          items:
            type: string
          description: Lista de titulares (Solo para cuentas corrientes)
        authorizedSigners:
          type: array
          items:
            type: string
          description: Lista de firmantes autorizados (Solo para cuentas corrientes)

        #FixedTerm fields
        allowedWithdrawal:
          type: string
          format: date
          description: Fecha permitida de retiro (Solo para cuentas a plazo fijo)

    BalanceResponse:
      type: object
      properties:
        accountNumber:
          type: string
          description: Número de cuenta
        accountType:
          type: string
          enum: [SAVINGS, CHECKING, FIXED_TERM]
          description: Tipo de cuenta
        currencyType:
          type: string
          enum: [PEN, USD]
          description: Tipo de moneda
        balance:
          type: number
          format: decimal
          description: Saldo de la cuenta

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: Fecha y hora del error
        path:
          type: string
          description: Ruta de la solicitud
        status:
          type: integer
          format: int32
          description: Código de estado HTTP
        error:
          type: string
          description: Mensaje de error corto
        requestId:
          type: string
          description: ID de la solicitud
        message:
          type: string
          description: Mensaje de error detallado

    TransactionResponse:
      type: object
      properties:
        id:
          type: string
          description: ID de la transacción
        accountNumber:
          type: string
          description: Numero de cuenta relacionado
        creditId:
          type: string
          description: Id de crédito relacionado
        fee:
          type: number
          format: decimal
          description: Comisión de la transacción
        transactionType:
          type: string
          enum: [ DEBIT, CREDIT, DEPOSIT, WITHDRAWAL, CREDIT_PAYMENT, CREDIT_DEPOSIT, CREDIT_CARD_CONSUMPTION, CREDIT_CARD_PAYMENT ]
          description: Tipo de transacción
        currencyType:
          type: string
          enum: [ PEN, USD ]
          description: Tipo de moneda
        amount:
          type: number
          format: decimal
          description: Monto de la transacción
        status:
          type: string
          enum: [ PENDING, COMPLETED, FAILED ]
          description: Estado de la transacción
        description:
          type: string
          description: Descripción de la transacción
        transactionDate:
          type: string
          format: date-time
          description: Fecha y hora de la transacción